DOMAIN = general/domain.lp general/global_domain.lp general/state_calculator.lp
INIT = general/init.lp
PLAN = general/plan.lp
HIDE_WARNING = -q2,2,2 --warn no-atom-undefined -V0
all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15

.SILENT:
test1:
	echo $@
	head -n2 tests/test1.lp
	@-clingo ${DOMAIN} ${INIT} tests/test1.lp ${HIDE_WARNING}
	head -n2 tests/test1.1.lp
	@-clingo ${DOMAIN} ${INIT} tests/test1.1.lp  ${HIDE_WARNING}
	echo ""

.SILENT:
test2:
	echo $@
	head -n2 tests/test2.lp
	@-clingo ${DOMAIN} tests/test2.lp   
	
	echo "" 
	head -n2 tests/test2.1.lp
	@-clingo ${DOMAIN} tests/test2.1.lp   ${HIDE_WARNING}

	echo "" 
	head -n2 tests/test2.2.lp
	@-clingo ${DOMAIN} tests/test2.2.lp   ${HIDE_WARNING}

	echo "" 
	head -n2 tests/test2.3.lp
	@-clingo ${DOMAIN} tests/test2.3.lp ${HIDE_WARNING}

	echo "" 
	head -n2 tests/test2.4.lp
	@-clingo ${DOMAIN} tests/test2.4.lp ${HIDE_WARNING}

	echo "" 
	head -n2 tests/test2.5.lp
	@-clingo ${DOMAIN} tests/test2.5.lp ${HIDE_WARNING}

	echo ""

.SILENT:
test3:
	echo $@
	head -n2 tests/test3.lp
	@-clingo ${DOMAIN} ${INIT} tests/test3.lp  ${HIDE_WARNING}

	echo ""
	head -n2 tests/test3.1.lp
	@-clingo ${DOMAIN} ${INIT} tests/test3.1.lp  ${HIDE_WARNING}

	echo ""

.SILENT:
test4:
	echo $@
	head -n2 tests/test4.lp
	@-clingo ${DOMAIN} tests/test4.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test4.1.lp
	@-clingo ${DOMAIN} tests/test4.1.lp ${HIDE_WARNING}
	
	echo ""
	head -n2 tests/test4.2.lp
	@-clingo ${DOMAIN} tests/test4.2.lp ${HIDE_WARNING}

	echo ""

.SILENT:
test5:
	echo $@
	head -n2 tests/test5.lp
	@-clingo ${DOMAIN} tests/test5.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.1.lp
	@-clingo ${DOMAIN} tests/test5.1.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.2.lp
	@-clingo ${DOMAIN} tests/test5.2.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.3.lp
	@-clingo ${DOMAIN} tests/test5.3.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.4.lp
	@-clingo ${DOMAIN} tests/test5.4.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.5.lp
	@-clingo ${DOMAIN} tests/test5.5.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.6.lp
	@-clingo ${DOMAIN} tests/test5.6.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.7.lp
	@-clingo ${DOMAIN} tests/test5.7.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test5.8.lp
	@-clingo ${DOMAIN} tests/test5.8.lp ${HIDE_WARNING}
	echo ""
	
.SILENT:
test6:
	echo $@
	head -n2 tests/test6.lp
	@-clingo ${DOMAIN} tests/test6.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.1.lp
	@-clingo ${DOMAIN} tests/test6.1.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.2.lp
	@-clingo ${DOMAIN} tests/test6.2.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.3.lp
	@-clingo ${DOMAIN} tests/test6.3.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.4.lp
	@-clingo ${DOMAIN} tests/test6.4.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.5.lp
	@-clingo ${DOMAIN} tests/test6.5.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.6.lp
	@-clingo ${DOMAIN} tests/test6.6.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.7.lp
	@-clingo ${DOMAIN} tests/test6.7.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.8.lp
	@-clingo ${DOMAIN} tests/test6.8.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.9.lp
	@-clingo ${DOMAIN} tests/test6.9.lp ${HIDE_WARNING}
	
	echo ""
	head -n2 tests/test6.10.lp
	@-clingo ${DOMAIN} tests/test6.10.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.11.lp
	@-clingo ${DOMAIN} tests/test6.11.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.12.lp
	@-clingo ${DOMAIN} tests/test6.12.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.13.lp
	@-clingo ${DOMAIN} tests/test6.13.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.14.lp
	@-clingo ${DOMAIN} tests/test6.14.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.15.lp
	@-clingo ${DOMAIN} tests/test6.15.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.16.lp
	@-clingo ${DOMAIN} tests/test6.16.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.17.lp
	@-clingo ${DOMAIN} tests/test6.17.lp ${HIDE_WARNING}

	echo ""
	head -n2 tests/test6.18.lp
	@-clingo ${DOMAIN} tests/test6.18.lp ${HIDE_WARNING}

	echo ""

.SILENT:
test7:

.SILENT:
test8:

.SILENT:
test9:
	echo $@
	head -n2 tests/test9.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test9.lp ${HIDE_WARNING}
	echo ""

.SILENT:
test10:
	echo $@
	head -n2 tests/test10.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test10.lp ${HIDE_WARNING}
	echo ""

# test other constraints
.SILENT:
test11:
	echo $@
	head -n2 tests/test11.lp
	@-clingo ${DOMAIN} tests/test11.lp ${HIDE_WARNING}
	echo ""

# test planning 
.SILENT:
test12:
	echo $@
	head -n2 tests/test12.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test12.lp ${HIDE_WARNING}
	echo ""

.SILENT:
test13:
	echo $@
	head -n2 tests/test13.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test13.lp ${HIDE_WARNING}
	echo ""
	
.SILENT:
test14:
	echo $@
	head -n2 tests/test14.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test14.lp ${HIDE_WARNING}
	echo ""

.SILENT:
test15:
	echo $@
	head -n2 tests/test15.lp
	@-clingo ${DOMAIN} ${PLAN} ${INIT} tests/test15.lp ${HIDE_WARNING}
	echo ""